### ISSUE TITLE
Rewrite content in Markdown

### ISSUE THREAD

**Issue by keeferrourke** [UoGSOCIS/uogsocis.github.io#105]
Jekyll support Markdown formatting. It would be nice if we could host our website content as a set of markdown files instead of HTML, since Markdown is easier to write and maintain.

This can probably be done using `pandoc` to convert HTML content wholesale into GitHub flavoured Markdown, and modifying our template files to use the `{ % include foo.md % }` directive.

**Comment by BenPearo** [comment]
Is it essential to keep all past event postings while doing this? I'd persist the info sections

**Comment by keeferrourke** [comment]
It might be nice to keep an event archive for historical reasons? We've been bad at keeping the event feed up to date though, so I'm not sure.

**Comment by BenPearo** [comment]
Looking into this more, it might be easier to regenerate the site and port the old posts and content lol

**Comment by BenPearo** [comment]
Check it out 😎
