### ISSUE TITLE
Restyle website

### ISSUE THREAD

**Issue by keeferrourke** [UoGSOCIS/uogsocis.github.io#106]
Our current website style is from ~2014 (and it shows!). It would be great if we could update the styles to make better use of whitespace, accommodate mobile and desktop displays of all sizes, and of course, also use our updated logos throughout.

**Comment by Capt-Titanium** [comment]
Can I work on this issue? I can rearrange your data, make the site responsive, add in better colors and insert animations which will make it look a little better.
