### ISSUE TITLE
Update about page with 2020 executive list

### ISSUE THREAD

**Issue by keeferrourke** [UoGSOCIS/uogsocis.github.io#109]
The title says it all! We're showing the wrong people!

**Comment by kinduff** [comment]
@keeferrourke do you have the updated list? Happy to do a PR for this

**Comment by BenPearo** [comment]
> 
> 
> @keeferrourke do you have the updated list? Happy to do a PR for this

Sorry, I should have sent a message claiming this. I just submitted a PR

**Comment by kinduff** [comment]
That's okay!

**Comment by keeferrourke** [comment]
Closed by #114
