### ISSUE TITLE
Style: let content breathe

### ISSUE THREAD

**Issue by keeferrourke** [UoGSOCIS/uogsocis.github.io#111]
This content is great, but it doesn't look great.

![image](https://user-images.githubusercontent.com/6888381/94961725-bcb58780-04e4-11eb-8670-705fa5aeca90.png)

By contrast, WOW look at the GWiCS website!

![image](https://user-images.githubusercontent.com/6888381/94961812-eec6e980-04e4-11eb-85ea-7d23b7dfbe9a.png)

**Comment by Shivangi-ch** [comment]
Hi @keeferrourke Can you assign this to me?

**Comment by keeferrourke** [comment]
Hi @Shivangi-ch are you a U of G student? We're limiting contributors to interested Guelph School of Computer Science students at the moment. If this is the case, please message me on [GryphSlack](https://gryph.slack.com), and I'll get you in touch with the committee that's redesigning the site this year.

**Comment by Shivangi-ch** [comment]
> Hi @Shivangi-ch are you a U of G student? We're limiting contributors to interested Guelph School of Computer Science students at the moment. If this is the case, please message me on [GryphSlack](https://gryph.slack.com), and I'll get you in touch with the committee that's redesigning the site this year.

I am not a student of UOG.

**Comment by keeferrourke** [comment]
Sorry @Shivangi-ch :( I can't assign this issue to you then.
