### ISSUE TITLE
Remove GCC, Roboticon, CSGames, and CUSEC from the header

### ISSUE THREAD

**Issue by BenPearo** [UoGSOCIS/uogsocis.github.io#132]
go into _includes/header.html and remove these pages from the header, but not the project

**Comment by danindugit** [comment]
I got this, but I might have some trouble with the pull-request process since I'm new to with working with more than 1 branch. If I have difficulties with it I'll let you know, but go ahead and assign me!

**Comment by BenPearo** [comment]
That’s okay. Let me know if you need guidance with the PR

**Comment by danindugit** [comment]
I've made the pull request. Let me know if I made any mistakes with the whole PR and branch creating process.
