### ISSUE TITLE
Page to feature University of Guelph Computer Science student projects?

### ISSUE THREAD

**Issue by Fogest** [UoGSOCIS/uogsocis.github.io#45]
It would be interesting to have a page that features things that the CS students have been up to. Whether it be a program to make students lives easier or a website geared toward everyone. It would be cool to feature what the CS students create!

**Comment by keeferrourke** [comment]
@NLaundry is this something that the @guelphcodingcommunity might be interested in doing for GCC's new website? Might go well with your 30-day project thing! :)

**Comment by keeferrourke** [comment]
Gonna close this issue though, since it's 6 years old, and might be better suited for a different CS club :)

(To subscribers of this issue, sorry for the notification!)
