### ISSUE TITLE
Hero needs some sort of alpha mask to make text more readable

### ISSUE THREAD

**Issue by jhorvat** [UoGSOCIS/uogsocis.github.io#59]
![screen shot 2014-11-11 at 11 18 53 am](https://cloud.githubusercontent.com/assets/4116475/4996300/ae85d260-6994-11e4-8236-afc8153817e6.png)

The text is pretty difficult to read on the homepage. We should add some sort of alpha to the hero so the text is easier to read

**Comment by alexpennells** [comment]
Fixed with the site reskin
