### ISSUE TITLE
Flow of the site on the main page

### ISSUE THREAD

**Issue by jhorvat** [UoGSOCIS/uogsocis.github.io#61]
![screen shot 2015-01-10 at 11 13 08 pm](https://cloud.githubusercontent.com/assets/4116475/5694335/7dd207ba-991e-11e4-9e26-b675a684a167.png)
This might just be me but I find the varying widths of the site to be pretty strange. I think to keep it consistent the white div should extend to the width of the page. Something like this:
![screen shot 2015-01-10 at 11 17 00 pm](https://cloud.githubusercontent.com/assets/4116475/5694341/df95bf82-991e-11e4-93a7-3b2e17e83bdc.png)

Thoughts?

**Comment by alexpennells** [comment]
Agreed. Updated.
