### ISSUE TITLE
Update about page with new exec

### ISSUE THREAD

**Issue by Fogest** [UoGSOCIS/uogsocis.github.io#64]
The about page should be updated to list the new executive members as well as possible include pictures as issue #4 brings up.

**Comment by SolitaryCipher** [comment]
This should really happen ASAP, with Orientation Week coming up soon

**Comment by Fogest** [comment]
Yes it definitely should. The team really has not had much communication yet, which also means lack of any kind of images to use.

**Comment by Fogest** [comment]
Done 

Commit f51682e55a53ee8891ed666f003c0b50f78deae9
